### ISSUE TITLE
Jumplist Controller

### ISSUE THREAD

**Issue by JarrodMFlesch** [faceless-ui/jumplist#4]
Found this jumplist with prev/next controls, abstract controls like this might be a cool addition.
[inspiration site](https://elium.studio/work)

**Comment by jacobsfletch** [comment]
I can see the value in a feature like this. Consider it done.

More than item can be active at one time, so we’d have to maintain some sort of `currentIndex` that is the top-left-most active item. One other note is that the previous / next controls should be able to be rendered individually to provide the most design freedom in terms of layout.

**Comment by jacobsfletch** [comment]
After looking into this a bit, we'd need to extract _some_ of the logic currently held with the `Jumplist` component into the `JumplistProvider` so that control can be distributed across multiple different components.
